apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dynamic-pyspark-pipelines
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]  # <-- add this
  generators:
    - git:
        repoURL: 'https://github.com/dato1999/topics.git'
        revision: HEAD
        files:
          - path: "*.json"
  template:
    metadata:
      name: 'spark-app-{{.path.filenameNormalized | trimSuffix ".json"}}'  # <-- dot + trimSuffix here too
    spec:
      project: default
      source:
        repoURL: 'https://github.com/dato1999/manifestrep.git'
        targetRevision: HEAD
        path: charts/spark-streaming-template
        helm:
          parameters:
            - name: "spark.jobName"
              value: 'spark-{{.path.filenameNormalized | trimSuffix ".json"}}'
            - name: "spark.topicName"
              value: "{{.topic_name}}"  # <-- dot
            - name: "spark.schemaDDL"
              value: "{{.schema}}"      # <-- dot
      destination:
        server: 'https://kubernetes.default.svc'
        namespace: spark-apps
      syncPolicy:
        automated:
          prune: true
          selfHeal: true